import LANG from '../languages/languages';

export default {
    Package: 'watch.aynaott.com', // Ayna OTT

    //***** please change below values to match the client
    AppPackageID: 'com.aynaott.apps', //this you can find in the Customer Notebook App details
    AppIsLauncher: false, //this need to be "false" unless you build a launcher app
    IsWebTV: false, //this for WebTV if yes set the value to true used only by Sander
    App_Version: 'V9.5.40', //we only change the last 2 digits if needed ONLY UP NEVER DOWN
    Default_Language: 'english', // choose the start language you can choose: arabic, burmese, dutch,
    Debug: false,

    Development: false,
    IsHomeLoaded: false,
    UseSocialLogin: false,
    SocialGoogle: false,
    SocialFacebook: false,
    SocialPhone: false,
    SocialEmail: false,
    IsBeta: false,
    CRM: '',
    CMS: '',
    IMS: '',
    Client: '',
    ImageUrlCMS: '',
    ImageUrlCRM: '',
    GuiBaseUrl: '',
    BigQueryUrl: '',
    BaseCdnUrl: '',
    CDN_Prefix: '',
    IMS_Prefix_Staging: '',
    Staging: false,

    //token
    DATA_TOKEN: '',
    USER_TOKEN: '',

    //keys
    AKAMAI_LEGACY_KEY: '5xxxxxxx26d439f66398b94',
    AKAMAI_KEY: '',
    FLUSSONIC: '',

    //PWA
    Device_IsPWA: false,
    Show_PWA_Message: false,
    Device_IsPwaAndroidChrome: false,
    Device_IsPwaIosChrome: false,
    Device_IsPwaIosSafari: false,
    Device_IsPwaAndroidSamsung: false,
    Device_IsPwaAndroid: false,
    Device_IsPwaIOS: false,
    Device_IsWebTvMobile: false,

    //device info
    Device_FormFactor: 'TV', //TV, TABLET, PHONE, WEB
    Device_Model: '',
    Device_Manufacturer: '',
    Device_Category: 'stb',
    Device_UUID: null,
    Device_OS_Version: '',
    Device_MacAddress: 'Not Set',
    Device_Serial: 'Not Set',
    Device_IpAddress: '',
    Device_Type: '_Generic_Android',
    Device_UserAgent: '',
    Device_Time: 0,
    Device_IsTablet: false,
    Device_IsTV: false,
    Device_IsPhone: false,
    Device_IsSTB: false,
    Device_IsWebTV: true,
    Device_IsSmartTV: false,
    Device_IsAppleTV: false,
    Device_IsAndroidTV: false,
    Device_IsFireTV: false,
    Device_HasNotch: false,
    Device_IsPortrait: 0,

    Device_HasEthernet: false,
    Device_IsSmallScreen: false,
    Device_UniqueID: 'Not Set',
    Device_System: '',
    WebOStoOld: false,
    Devices: [],

    //network
    Network_IpAddress: '',
    Network_Type: '',
    Network_Name: '',
    Network_ISP: '',
    Network_IsVPN: false,
    Network_IsProxy: false,
    Network_ASN: '',

    //
    Location_ZIP: '',
    Location_City: '',
    Location_State: '',
    Location_Country: '',
    Location_Latitude: '',
    Location_Longitude: '',
    Location_Timezone: '',

    //purchase
    ExternalPurchaseUrl: '',
    ExternalPurchaseApi: '',
    CreditCardPayment: false,
    PaypalPayment: false,
    Payment_Method: 'subscription',
    User_Currency: 'EUR',

    Rented_Movies: [],
    Rented_Series: [],
    Rented_Seasons: [],
    Rented_Episodes: [],
    Rented_Albums: [],
    Rended_Songs: [],
    Rented_Apps: [],

    //styled popup
    PopupText: '',
    PopupImage: '',

    //screen
    BUTTON_MARGIN: 2,
    Menu_Width: 0,
    Device_Width: 0,
    Device_Height: 0,
    Portrait_Width: 0,
    Landscape_Width: 0,
    Extra_Padding: 0,

    COL_1: 0, //1 big column
    COL_2: 0, //2 columns
    COL_3: 0, //3 columns
    COL_4: 0, //4 columns
    COL_5: 0, //5 columns
    COL_6: 0, //6 columns
    COL_7: 0, //7 columns
    COL_8: 0, //8 columns
    COL_9: 0, //9 columns
    COL_10: 0, //10 columns

    ROW_1: 0,
    ROW_1: 0,
    ROW_2: 0,
    ROW_3: 0,
    ROW_4: 0,
    ROW_5: 0,
    ROW_6: 0,
    ROW_7: 0,
    ROW_8: 0,
    ROW_9: 0,
    ROW_10: 0,

    COL_REMAINING_1: 0, //1 big column
    COL_REMAINING_2: 0, //2 columns
    COL_REMAINING_3: 0, //3 columns
    COL_REMAINING_4: 0, //4 columns
    COL_REMAINING_5: 0, //5 columns
    COL_REMAINING_6: 0, //6 columns
    COL_REMAINING_7: 0, //7 columns
    COL_REMAINING_8: 0, //8 columns
    COL_REMAINING_9: 0, //9 columns
    COL_REMAINING_10: 0, //10 columns

    //app info
    App_Theme: 'Default',
    User_Agent: null,

    //drm new
    DRM_Key: '',
    DRM_Type: '',
    DRM_AccountID: '',
    DRM_CertificateUrl: '',
    DRM_LicenseServer: '',
    DRM_LicenseKeyApple: '',
    DRM_LicenseServerApple: '',
    DRM_KeyServerURL: '',

    //data storage
    EPG_Row: 0,
    EPG_RowHeight: 0,
    EPG_Paging: 0,
    EPG_Channel: [],
    EPG_GridHeight: 0,
    EPG_Focussed_Program: 0,
    EPG_Focussed_Row: 0,
    EPG_Focussed_Last_Program: false,
    EPG_Focussed_First_Program: false,
    Channels_Selected_Category_Index: 0,
    EPG_Paging_Page: 0,
    Casting: false,
    UserInterface: {
        app_state_change: {
            restart_app: true,
            restart_stream: true,
        },
        authentication: {
            lock_device_to_ip_address: false,
        },
        channel: {
            enable_sorting_channels: true,
            enable_toggle_channels: true,
            show_channel_preview: true,
            toggle_default_settings: 'User Defined',
        },
        general: {
            catchup_days: 4,
            clock_format: '24 Hrs',
            enable_catchuptv: true,
            enable_clock: true,
            enable_favourites_menu: true,
            enable_kids_mode_profile: true,
            enable_large_fonts: false,
            enable_messages_menu: true,
            enable_profiles: true,
            enable_recordings: true,
            enable_search_menu: true,
            enable_settings_menu: true,
            enable_watchlist_menu: true,
            enable_weather: true,
            epg_days: 7,
            sleep_mode_setting: 180,
            start_screen: 'Home',
        },
        home: {
            enable_ads: true,
            enable_hero_images: true,
            enable_news_section: true,
            enable_tv_preview: true,
        },
        player: {
            default_audio_language: 'User Defined',
            default_screen_mode: 'User Defined',
            default_subtitle_language: 'User Defined',
            enable_casting: true,
            enable_catchup_buttons: true,
            enable_channel_menu: true,
            enable_mini_epg: true,
            enable_problem_report: true,
            enable_quadview: true,
            enable_watermarking: true,
            player_type: 'Full Player (default)',
        },
        series: {
            enable_episodes_full_metadata: true,
        },
        tv_guide: {
            enable_epg_search: true,
            enable_tv_preview_screen: true,
            show_epg_preview: true,
        },
    },
    Channel: [],
    Channels_Selected: null,
    Channels_Selected_Category_ID: -999,
    Channels_Selected_Index: 0,
    Channel_Index: 0,
    Channels_Selected_Row: 0,
    Channels_Catchup: [],
    EPG_Program: [],

    Catchup_Selected: [],
    Catchup_Selected_Index: 0,
    Catchup_Selected_Program: [],

    Store_Selected_Index: 0,
    Store_Sub_Selected_Index: 0,

    Movie_Selected: null,
    Movie_Selected_Index: 0,
    Movie_Selected_Category_ID: 0,
    Movie_Selected_Row: 0,

    Tag_Selected_Index: 0,
    Tag_Selected_Row: 0,

    EPG_Selected_Row: 0,

    Education_Selected: null,
    Education_Selected_Index: 0,
    Education_Selected_Index: 0,
    Education_Selected_Level: null,
    Education_Selected_Level_ID: 0,
    Education_Selected_Course_Index: 0,
    Education_Selected_Course_Row: 0,
    Year_Index: 0,

    Education: [],
    Course: [],
    Education_Level_Index: 0,
    Education_Year_Index: 0,
    Education_Course_Index: 0,
    Education_Lesson_Index: 0,

    Series_Selected: null,
    Series_Selected_Index: 0,
    Season_Selected_Index: 0,
    Season_Selected_Season: null,
    Season_Selected_Season_ID: 0,
    Season_Selected_Episode_Index: 0,
    Season_Selected_Episode_Row: 0,

    Home_Screen_Ads_Date: 0,
    Home_Screen_Ads: null,
    Home_Screen_Ads_Date_Vertical: 0,
    Home_Screen_Ads_Vertical: null,
    Home_Screen_Ads_Date_Horizontal: 0,
    Home_Screen_Ads_Horizontal: null,

    Albums_Selected_Index: 0,
    Apps_Selected_Index: 0,
    Recording_Selected_Index: 0,
    InAppPurchase: false,

    EPG_Search_Channels: [],
    EPG_Search_EPG: [],
    SearchPrograms: [],
    ProgramSearch_: [],
    ProgramSearch: [],
    SubMenuOpened: false,
    Android_Download_Enabled: false,
    Android_Download_Link: '',
    IOS_Download_Enabled: false,
    IOS_Download_Link: '',
    Catchup_DVR_Offset: 120,
    Minutes: [
        { key: '2 Mins', value: 120 },
        { key: '5 Mins', value: 300 },
        { key: '7 Mins', value: 420 },
        { key: '10 Mins', value: 600 },
        { key: '12 Mins', value: 720 },
        { key: '15 Mins', value: 900 },
    ],
    Account_Type: [
        {
            name: LANG.getTranslation('kids_account'),
            value: 'kids mode',
            checked: false,
        },
        {
            name: LANG.getTranslation('regular_account'),
            value: 'regular',
            checked: true,
        },
    ],
    Profile_Ratings: [
        { rating: 'TV-12', checked: false },
        { rating: 'TV-14', checked: false },
        { rating: 'TV-16', checked: false },
        { rating: 'TV-18', checked: false },
        { rating: 'TV-21', checked: false },
        { rating: 'TV-ALL', checked: true },
    ],
    Profile_Locks: [
        {
            name: LANG.getTranslation('not_locked'),
            value: 'not_locked',
            checked: true,
        },
        { name: LANG.getTranslation('locked'), value: 'locked', checked: false },
    ],
    M3U_Playlist_Url: '', // 'https://cloudtv.akamaized.net/docs/playlist5.m3u', //'https://cloudtv.akamaized.net/docs/playlist5.m3u', // 'http://playlist.tvms.io/playlist?user=77043454&pass=759005&cms=PS_Content&crm=PS_CRM&client=ps',
    ShowMenu: false,
    Loaded: false,
    HomePlayChannelStarted: false,
    DirectToTelevision: false,
    Age_Rating: 'ALL',
    PlayServices: false,
    Beacon_URL: '',
    Hamburger: false,
    Selected_Service: 0,
    Selected_Profile: '',
    Authenticated: false,
    Selected_Language: '',
    Favorite_Education: [],
    EducationStores: [],
    SupportPages: [],
    MenuBase: [],
    EPG_CatchupTV: [],
    Logout: false,
    ViaHome: false,
    Profile_Is_Selected: false,
    Profiled: false,
    Languaged: false,
    TV_StartTime: 0,
    TV_EndTime: 0,
    TV_Channel: [],
    TV_Program: [],
    TV_EpgIndex: 0,
    Favorite_Movies: [],
    Favorite_Series: [],
    EPG_Width: 0,
    EPG_Height: 0,
    HTTPvsHTTPS: 'https://', //https is mandatory from now on
    Ads_Enabled: true,
    Connected_Internet: true,
    Reseller: [],
    SupportText: '',
    Video_Quality_Setting: 'HIGH',
    Kids_Mode: 'no kids mode', //set to false for kidsmode
    Movie_Tags: [],
    OTA_Updates: [],
    OTA_Update: false,
    Messages: [],
    Updates: [],
    Messages_QTY: 0,
    UI_LoadedTZ: 0,
    UI_Profile: null,
    Tags: [],
    Show_Error: '',
    Focus: 'Home',
    PIN_SET: false,
    Screen_Size: 'contain',
    Show_Weather: false,
    Disclaimer: '',
    Show_Disclaimer: false,
    Message_Center_Shown: false,
    EPG_TODAY: [],
    Device_Apps: [],
    Subscription_Push: [],
    PushNotifications: [],
    Shown_Notifications: [],
    IsCasting: false,
    Login_Check_Date: '',
    SearchContent: [],
    SearchChannels: [],
    SearchChannelsExtra: [],
    SearchMovies: [],
    SearchSeries: [],
    SearchApps: [],
    SearchMusic: [],
    SearchChannels_: [],
    SearchMovies_: [],
    SearchSeries_: [],
    SearchApps_: [],
    SearchMusic_: [],
    Settings_Login: [],
    Services_Login: [],
    Services: [],
    Settings_Services_Login: [],
    Settings_Gui: [],
    User: [],
    Product: [],
    Metro: [],
    Menu: [],
    Channels: [],
    Channels_Categories: [],
    Favorite_Channels: [],
    EPG: [],
    EPG_Days: 0,
    EPG_Catchup: [],
    EPG_Catchup_Channel: [],
    EPG_TODAY_Catchup: [],
    EPG_DATE_LOADED: '',
    Programs: [],
    Selected_VodID: 0,
    Selected_MovieID: 0,
    Selected_MovieIndex: 0,
    Selected_Movies_From: 'Home',
    Progress_Seasons: [],
    Progress_Episodes: [],
    Series: [],
    Season: [],
    Selected_SeriesID: 0,
    Selected_SeriesIndex: 0,
    Apps: [],
    Apps_Categories: [],
    Albums: [],
    Album_Categories: [],
    Selected_AlbumIndex: 0,
    Selected_Next_Category_Index: 0,
    Watched_Movies: [],
    Progress_Movies: [],
    Progress_Television: [],
    MovieStores: [],
    Movies: [],
    Movie: [],
    Is_Trailer: false,
    SeriesStores: [],
    Selected_ID_Player: 0,
    Season_Index: 0,
    Series_Index: 0,
    Episode_Index: 0,
    URL: '',
    URL_Type: '',
    Recordings: [],
    Recording: [],
    PPV: [],
    Payment_Type: '',
    Has_Storage: false,
    Has_Wallet: false,
    YT_Videos: [],
    YT_Categories: [],
    YT_VideoIndex: 0,
    Youtube_Key: 'AIzaS3ZcBuU7hMoh5oEZDyoIqpCTM',
    Recording: [],
    AutoLogin: false,
    Channel_Toggle: 'Toggle View',
    Menu_Type: 'full',
    Clock_Type: 'AM/PM',
    Clock_Setting: 'hh:mm A',
    Clock_Not_Set: false,
    Have_Vod: false,
    Sleep_Mode: 180,
    Metro_Check_Date: '',
    Storage_Hours: 0,
    HasService: false,
    //general vars
    Profiles: [],
    ProfileID: 0,
    SearchInput: '',
    Selected_Profile: [],
    Childlock_Channels: [],
    Selected_AudioTrack: '',
    Selected_TextTrack: '',
    Has_Been_Registered: false,
    Orientation: '',
    Product_Json_Location: '',
    Show_Login_Page: false,
    Selected_CategoryID_Channels: 0,
    Selected_Channel: 0,
    ProductID: '',
    UserID: '',
    Pass: '',
    ServiceID: '',
    PIN: '0000',
    Logo: 'https://',
    Background: 'https://',
    Support: '',
    Button_Color: 'black',
    Selection_Color: '#333',
    Default_Button: 'Home',
    City: 'New York',
    State: 'New York',
    Country: 'United States',
    Longitude: '',
    Latitude: '',
    Timezone: '',
    Max_Devices: '',
    ResellerID: '0',
    Storage_Total: 0,
    Storage_Used: 0,
    Wallet_Credits: 0,
    Languages: [
        'Deutsch',
        'English',
        'Español',
        'Français',
        'Nederlands',
        'Papiamento',
        'Русский',
        'Polski',
        'Português',
        'हिन्दुस्तानी',
        'العربية',
        'फिजी बात',
        'မြန်မာစာ or မြန်မာစကား',
        'کوردی',
    ],
    show_log: false,
};
